[package]
name = "test_helper"
version = "0.0.1"
edition = "2021"

[package.metadata]

[package.metadata.component]

[package.metadata.component.target]
path = "wit-generated"

[package.metadata.component.target.dependencies]
"test:helper-exports" = { path = "wit-generated/deps/test_helper-exports" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []

[dependencies]
wit-bindgen-rt = { workspace = true }
